import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/global/header';
import { Footer } from '@/components/global/footer';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="pt-BR">
         <body>
            <section className="min-h-[calc(100vh+10rem)] flex flex-col">
               <Header />
               {children}
               <Footer />
            </section>
         </body>
      </html>
   );
}
